/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PurchaseAnalyticsListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onThePurchaseAnalyticsList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onThePurchaseAnalyticsList.onFilterBar().iCheckFilterField("{i18n>PO_ID}");
            Then.onThePurchaseAnalyticsList.onFilterBar().iCheckFilterField("{i18n>COMPANY_NAME}");
            Then.onThePurchaseAnalyticsList.onFilterBar().iCheckFilterField("{i18n>Currency}");
            Then.onThePurchaseAnalyticsList.onFilterBar().iCheckFilterField("{i18n>DESCRIPTION}");
            Then.onThePurchaseAnalyticsList.onFilterBar().iCheckFilterField("{i18n>COUNTRY}");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onThePurchaseAnalyticsList.onTable().iCheckColumns(undefined, {"PurchaseOrderId":{"header":"{i18n>PO_ID}"},"ItemPositition":{"header":"ItemPositition"},"CompanyName":{"header":"{i18n>COMPANY_NAME}"},"GroosAmount":{"header":"{i18n>GROSS_AMOUNT}"},"Currency":{"header":"{i18n>Currency}"},"Description":{"header":"{i18n>DESCRIPTION}"},"OverallStatus":{"header":"{i18n>OVERALL_STATUS}"},"Country":{"header":"{i18n>COUNTRY}"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onThePurchaseAnalyticsList.onFilterBar().iExecuteSearch();
            
            Then.onThePurchaseAnalyticsList.onTable().iCheckRows();

            When.onThePurchaseAnalyticsList.onTable().iPressRow(0);
            Then.onThePurchaseAnalyticsObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});